//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeScheduler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeScheduler.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current date isn&apos;t completed..
        /// </summary>
        public static string CurrentDateNotCompleted {
            get {
                return ResourceManager.GetString("CurrentDateNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current date is out of range..
        /// </summary>
        public static string CurrentDateOutOfRange {
            get {
                return ResourceManager.GetString("CurrentDateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every day. Schedule will be used on {0} at {1} every {2} between {3} and {4} starting on {5} and ending on {6}..
        /// </summary>
        public static string DailyDescription {
            get {
                return ResourceManager.GetString("DailyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dateTime isn&apos;t completed..
        /// </summary>
        public static string DateTimeNotCompleted {
            get {
                return ResourceManager.GetString("DateTimeNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled is false..
        /// </summary>
        public static string EnabledIsFalse {
            get {
                return ResourceManager.GetString("EnabledIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date is less than start date..
        /// </summary>
        public static string EndDateIsLessThanStartDate {
            get {
                return ResourceManager.GetString("EndDateIsLessThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end time is less than the start time..
        /// </summary>
        public static string EndTimeIsLessThanStartDate {
            get {
                return ResourceManager.GetString("EndTimeIsLessThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every day.
        /// </summary>
        public static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every month is negative..
        /// </summary>
        public static string EveryMonthIsNegative {
            get {
                return ResourceManager.GetString("EveryMonthIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every month is zero..
        /// </summary>
        public static string EveryMonthIsZero {
            get {
                return ResourceManager.GetString("EveryMonthIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs {0}. Schedule will be used on {1} at {2} starting on {3} and ending on {4}..
        /// </summary>
        public static string ExecutionDescription {
            get {
                return ResourceManager.GetString("ExecutionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Closing.
        /// </summary>
        public static string FormClosing {
            get {
                return ResourceManager.GetString("FormClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frequency days is negative..
        /// </summary>
        public static string FrequencyDaysIsNegative {
            get {
                return ResourceManager.GetString("FrequencyDaysIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frequency days is zero..
        /// </summary>
        public static string FrequencyDaysIsZero {
            get {
                return ResourceManager.GetString("FrequencyDaysIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of month is negative..
        /// </summary>
        public static string MonthDayIsNegative {
            get {
                return ResourceManager.GetString("MonthDayIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of month is zero..
        /// </summary>
        public static string MonthDayIsZero {
            get {
                return ResourceManager.GetString("MonthDayIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs the {0} of every {1} months every {2} between {3} and {4} starting on {5} and ending on {6}..
        /// </summary>
        public static string MonthlyDescription {
            get {
                return ResourceManager.GetString("MonthlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scheduler isn&apos;t enabled..
        /// </summary>
        public static string NotEnabled {
            get {
                return ResourceManager.GetString("NotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No week days selected..
        /// </summary>
        public static string NoWeekDaysSelected {
            get {
                return ResourceManager.GetString("NoWeekDaysSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs once time is out of range..
        /// </summary>
        public static string OccursOnceTimeIsOutOfRange {
            get {
                return ResourceManager.GetString("OccursOnceTimeIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once date time is less than current date..
        /// </summary>
        public static string OnceDateTimeLessThanCurrentDate {
            get {
                return ResourceManager.GetString("OnceDateTimeLessThanCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs once. Schedule will be used on {0} at {1} starting on {2} and ending {3}..
        /// </summary>
        public static string OnceDescription {
            get {
                return ResourceManager.GetString("OnceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every {0} weeks on {1} {2} between {3} and {4} starting on {5} and ending on {6}..
        /// </summary>
        public static string RecurringDescription {
            get {
                return ResourceManager.GetString("RecurringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date isn&apos;t completed..
        /// </summary>
        public static string StartDateNotCompleted {
            get {
                return ResourceManager.GetString("StartDateNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date can&apos;t be represented..
        /// </summary>
        public static string TheDateCannotBeRepresented {
            get {
                return ResourceManager.GetString("TheDateCannotBeRepresented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The times of time unit is negative..
        /// </summary>
        public static string TheNumberOfTimeUnitIsNegative {
            get {
                return ResourceManager.GetString("TheNumberOfTimeUnitIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The times of time unit is zero..
        /// </summary>
        public static string TheNumberOfTimeUnitIsZero {
            get {
                return ResourceManager.GetString("TheNumberOfTimeUnitIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The week frequency is negative..
        /// </summary>
        public static string TheWeekFrequencyIsNegative {
            get {
                return ResourceManager.GetString("TheWeekFrequencyIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The week frequency is zero..
        /// </summary>
        public static string TheWeekFrequencyIsZero {
            get {
                return ResourceManager.GetString("TheWeekFrequencyIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every {0} weeks on {1} every {2} between {3} and {4} starting on {5} and ending on {6}..
        /// </summary>
        public static string WeeklyDescription {
            get {
                return ResourceManager.GetString("WeeklyDescription", resourceCulture);
            }
        }
    }
}
