//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeScheduler.Test.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeScheduler.Test.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs Once. Schedule will be used on 01/01/2000 at 00:00 starting on 01/01/2000 00:00:00 and ending on 01/01/2000 00:00:00..
        /// </summary>
        internal static string DescriptionOnce {
            get {
                return ResourceManager.GetString("DescriptionOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every 2 weeks on monday, tuesday, wednesday, thursday, friday, saturday and sunday every 2 seconds between 00:00:00 and 00:00:00 starting on 01/01/2000 and ending on 01/01/2000..
        /// </summary>
        internal static string DescriptionRecurringAllDays {
            get {
                return ResourceManager.GetString("DescriptionRecurringAllDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every 2 weeks on monday every 2 hours between 00:00:00 and 00:00:00 starting on 01/01/2000 00:00:00 and ending on 01/01/2000 00:00:00..
        /// </summary>
        internal static string DescriptionRecurringEveryHours {
            get {
                return ResourceManager.GetString("DescriptionRecurringEveryHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every 2 weeks on monday every 2 minutes between 00:00:00 and 00:00:00 starting on 01/01/2000 00:00:00 and ending on 01/01/2000 00:00:00..
        /// </summary>
        internal static string DescriptionRecurringEveryMinutes {
            get {
                return ResourceManager.GetString("DescriptionRecurringEveryMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every 2 weeks on monday every 2 seconds between 00:00:00 and 00:00:00 starting on 01/01/2000 00:00:00 and ending on 01/01/2000 00:00:00..
        /// </summary>
        internal static string DescriptionRecurringEverySeconds {
            get {
                return ResourceManager.GetString("DescriptionRecurringEverySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every 2 weeks on monday once at 00:00:00 between 00:00:00 and 00:00:00 starting on 01/01/2000 00:00:00 and ending on 01/01/2000 00:00:00..
        /// </summary>
        internal static string DescriptionRecurringOnce {
            get {
                return ResourceManager.GetString("DescriptionRecurringOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every 2 weeks on monday and tuesday every 2 seconds between 00:00:00 and 00:00:00 starting on 01/01/2000 00:00:00 and ending on 01/01/2000 00:00:00..
        /// </summary>
        internal static string DescriptionRecurringTwoDays {
            get {
                return ResourceManager.GetString("DescriptionRecurringTwoDays", resourceCulture);
            }
        }
    }
}
